version: "3.9"
services:
  backend:
    build: ./backend
    container_name: otakulist-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # - JIKAN_ENABLED=true
    volumes:
      - db_data:/app/data
  frontend:
    build: ./frontend
    container_name: otakulist-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
volumes:
  db_data:
